// General, low-impact, home exercises commonly recommended for people with
// osteoporosis and knee discomfort: weight-bearing + gentle resistance moves,
// no forward spine bending, no twisting, no jumping/running.
// Source guidance: Mayo Clinic, Bone Health & Osteoporosis Foundation.

export const exercises = [
  {
    id: "ankle-pumps",
    name_en: "Ankle Pumps & Circles",
    name_hi: "टखने का व्यायाम",
    reps: "10 pumps + 10 circles, both feet",
    reps_hi: "10 बार ऊपर-नीचे + 10 बार गोल घुमाएं, दोनों पैर",
    why_en: "Warms up the joints and gets blood moving before anything else.",
    why_hi: "जोड़ों को गर्म करता है और खून का प्रवाह बढ़ाता है।",
    steps_en: [
      "Sit tall in a sturdy chair, feet resting on the floor.",
      "Lift your toes up and down slowly (ankle pumps).",
      "Then rotate each ankle in slow circles, both directions.",
    ],
    steps_hi: [
      "एक मजबूत कुर्सी पर सीधे बैठें, पैर ज़मीन पर रखें।",
      "पंजों को धीरे-धीरे ऊपर-नीचे करें।",
      "फिर हर टखने को धीरे-धीरे दोनों दिशाओं में घुमाएं।",
    ],
    videoId: "n6HI30C00Bk",
    videoSource: "VNA Health Group",
  },
  {
    id: "seated-marching",
    name_en: "Seated Marching",
    name_hi: "बैठकर मार्च करना",
    reps: "10 lifts each leg",
    reps_hi: "हर पैर से 10 बार",
    why_en: "Gently strengthens hip and thigh muscles without standing.",
    why_hi: "बिना खड़े हुए कूल्हे और जांघ की मांसपेशियों को मज़बूत करता है।",
    steps_en: [
      "Sit tall, hands resting on the chair sides for support.",
      "Slowly lift one knee toward your chest, as high as is comfortable.",
      "Lower it down with control. Repeat with the other leg.",
    ],
    steps_hi: [
      "सीधे बैठें, हाथों को कुर्सी के किनारों पर रखें।",
      "एक घुटने को धीरे-धीरे छाती की ओर उठाएं, जितना आराम से हो सके।",
      "धीरे-धीरे नीचे लाएं। दूसरे पैर से दोहराएं।",
    ],
    videoSearch: "seated marching exercise for seniors",
  },
  {
    id: "quad-sets",
    name_en: "Quad Sets (Thigh Tightening)",
    name_hi: "जांघ कसने का व्यायाम",
    reps: "Hold 5 seconds, 10 times each leg",
    reps_hi: "5 सेकंड रोकें, हर पैर से 10 बार",
    why_en: "Strengthens the muscle that supports and protects the knee joint.",
    why_hi: "घुटने के जोड़ को सहारा देने वाली मांसपेशी को मज़बूत करता है।",
    steps_en: [
      "Sit or lie down with your leg straight out in front of you.",
      "Tighten the muscle on top of your thigh, pressing the knee down gently.",
      "Hold, then relax. Repeat with the other leg.",
    ],
    steps_hi: [
      "बैठें या लेटें, पैर सीधा सामने रखें।",
      "जांघ के ऊपर की मांसपेशी को कसें, घुटने को हल्के से नीचे दबाएं।",
      "रोकें, फिर ढीला करें। दूसरे पैर से दोहराएं।",
    ],
    videoId: "au62CidApd0",
    videoSource: "Ask Doctor Jo",
  },
  {
    id: "straight-leg-raise",
    name_en: "Straight Leg Raise (Lying Down)",
    name_hi: "लेटकर पैर उठाना",
    reps: "8–10 lifts each leg",
    reps_hi: "हर पैर से 8–10 बार",
    why_en: "Builds hip and thigh strength while keeping the knee still and safe.",
    why_hi: "घुटने को स्थिर रखते हुए कूल्हे और जांघ की ताकत बढ़ाता है।",
    steps_en: [
      "Lie on your back, one knee bent with foot flat, other leg straight.",
      "Tighten the straight leg's thigh muscle and lift it slowly, knee locked gently straight.",
      "Raise only as high as the opposite bent knee, then lower slowly.",
    ],
    steps_hi: [
      "पीठ के बल लेटें, एक घुटना मोड़ें, दूसरा पैर सीधा रखें।",
      "सीधे पैर की जांघ को कसें और धीरे-धीरे उठाएं, घुटना सीधा रखें।",
      "दूसरे मुड़े घुटने जितना ही ऊपर उठाएं, फिर धीरे नीचे लाएं।",
    ],
    videoId: "0c_NU1b8KCo",
    videoSource: "Physical Therapy Exercises",
  },
  {
    id: "heel-raises",
    name_en: "Standing Heel Raises",
    name_hi: "खड़े होकर एड़ी उठाना",
    reps: "10 raises, holding a chair",
    reps_hi: "10 बार, कुर्सी पकड़कर",
    why_en: "A gentle weight-bearing move that helps protect bone density in the legs.",
    why_hi: "यह पैरों की हड्डी को मजबूत रखने में मदद करता है।",
    steps_en: [
      "Stand behind a sturdy chair, holding the back with both hands.",
      "Slowly rise onto your toes, lifting both heels off the floor.",
      "Lower back down with control. Keep knees soft, not locked.",
    ],
    steps_hi: [
      "एक मजबूत कुर्सी के पीछे खड़े हों, दोनों हाथों से पकड़ें।",
      "धीरे-धीरे पंजों पर उठें, दोनों एड़ियां ज़मीन से ऊपर करें।",
      "नियंत्रण के साथ नीचे आएं। घुटने हल्के मुड़े रहने दें।",
    ],
    videoId: "jbh9Wzt2Lfk",
    videoSource: "Physical Therapy Exercises",
  },
  {
    id: "hip-side-raise",
    name_en: "Standing Side Leg Raise",
    name_hi: "खड़े होकर पैर बगल में उठाना",
    reps: "8–10 each leg, holding a chair",
    reps_hi: "हर पैर से 8–10 बार, कुर्सी पकड़कर",
    why_en: "Strengthens hip muscles that support balance and reduce fall risk.",
    why_hi: "संतुलन बनाए रखने वाली कूल्हे की मांसपेशियों को मज़बूत करता है।",
    steps_en: [
      "Stand tall behind a chair, holding on with both hands.",
      "Keeping your leg straight, lift it slowly out to the side.",
      "Lower with control. Do not lean or twist your body.",
    ],
    steps_hi: [
      "कुर्सी के पीछे सीधे खड़े हों, दोनों हाथों से पकड़ें।",
      "पैर को सीधा रखते हुए धीरे-धीरे बगल में उठाएं।",
      "नियंत्रण के साथ नीचे लाएं। शरीर को मोड़ें या झुकाएं नहीं।",
    ],
    videoId: "qBqKuEQl9sI",
    videoSource: "Ask Doctor Jo",
  },
  {
    id: "chair-squats",
    name_en: "Sit-to-Stand (Chair Squats)",
    name_hi: "कुर्सी से उठना-बैठना",
    reps: "5–8 repetitions",
    reps_hi: "5–8 बार",
    why_en: "One of the best weight-bearing exercises for leg and bone strength.",
    why_hi: "पैर और हड्डी की मज़बूती के लिए सबसे अच्छे व्यायामों में से एक।",
    steps_en: [
      "Sit at the front edge of a sturdy chair, feet flat, hands on armrests.",
      "Lean slightly forward and press through your feet to stand up slowly.",
      "Turn and lower yourself back down with control. Do not drop into the seat.",
    ],
    steps_hi: [
      "मजबूत कुर्सी के आगे के किनारे पर बैठें, पैर सपाट रखें, हाथ आर्मरेस्ट पर।",
      "थोड़ा आगे झुकें और पैरों के बल धीरे-धीरे खड़े हों।",
      "मुड़कर नियंत्रण के साथ नीचे बैठें। अचानक न बैठें।",
    ],
    videoId: "eutszbtbJM8",
    videoSource: "Wellen",
  },
  {
    id: "wall-pushups",
    name_en: "Wall Push-Ups",
    name_hi: "दीवार पर पुश-अप",
    reps: "8–10 repetitions",
    reps_hi: "8–10 बार",
    why_en: "Builds upper-body and wrist strength safely, useful for daily tasks.",
    why_hi: "ऊपरी शरीर और कलाई को सुरक्षित रूप से मज़बूत करता है।",
    steps_en: [
      "Stand an arm's length from a wall, palms flat against it at shoulder height.",
      "Bend your elbows and lean toward the wall slowly.",
      "Push back to standing. Keep your back straight throughout.",
    ],
    steps_hi: [
      "दीवार से एक हाथ की दूरी पर खड़े हों, हथेलियां कंधे की ऊंचाई पर रखें।",
      "कोहनी मोड़ें और धीरे-धीरे दीवार की ओर झुकें।",
      "वापस सीधे खड़े हो जाएं। पीठ सीधी रखें।",
    ],
    videoId: "wIPJvBQs7RA",
    videoSource: "Physical Therapists",
  },
  {
    id: "balance-hold",
    name_en: "Standing Balance Hold",
    name_hi: "खड़े होकर संतुलन",
    reps: "10–15 seconds, both sides",
    reps_hi: "10–15 सेकंड, दोनों तरफ",
    why_en: "Improves balance and lowers fall risk, which matters most with fragile bones.",
    why_hi: "संतुलन सुधारता है और गिरने का खतरा कम करता है।",
    steps_en: [
      "Stand behind a chair, one hand lightly on it for safety.",
      "Shift your weight slightly onto one leg, just barely lifting the other foot.",
      "Hold steady, breathing normally, then switch sides.",
    ],
    steps_hi: [
      "कुर्सी के पीछे खड़े हों, सुरक्षा के लिए एक हाथ हल्के से रखें।",
      "अपना वज़न एक पैर पर थोड़ा डालें, दूसरे पैर को हल्का ऊपर उठाएं।",
      "स्थिर रहें, सामान्य सांस लें, फिर दूसरी तरफ करें।",
    ],
    videoId: "Dtgh2_LFkBQ",
    videoSource: "Ask Doctor Jo",
  },
  {
    id: "gentle-walk",
    name_en: "Gentle Walk",
    name_hi: "हल्की सैर",
    reps: "5–10 minutes, comfortable pace",
    reps_hi: "5–10 मिनट, आरामदायक गति",
    why_en: "Walking is weight-bearing and one of the simplest ways to protect bone density.",
    why_hi: "चलना हड्डी को मज़बूत रखने का सबसे आसान तरीका है।",
    steps_en: [
      "Wear supportive, flat, non-slip footwear.",
      "Walk at home, in a corridor, or a flat, even outdoor path.",
      "Use a stick, walker, or wall support if it feels safer.",
    ],
    steps_hi: [
      "आरामदायक, सपाट, फिसलन-रहित जूते पहनें।",
      "घर में, गलियारे में, या समतल रास्ते पर चलें।",
      "यदि ज़रूरत हो तो छड़ी, वॉकर या दीवार का सहारा लें।",
    ],
  },
];

// Things to avoid. Kept visible so the routine never drifts toward these.
export const avoidList = [
  { en: "Jumping, running, or jogging", hi: "कूदना, दौड़ना" },
  { en: "Toe touches or sit-ups (forward bending of the spine)", hi: "पंजे छूना या सिट-अप (रीढ़ को आगे मोड़ना)" },
  { en: "Twisting the waist quickly or forcefully", hi: "कमर को तेज़ी से मोड़ना" },
  { en: "Any exercise that causes pain. Stop and rest instead", hi: "दर्द देने वाला कोई भी व्यायाम। रुकें और आराम करें" },
];
